### ISSUE TITLE
ValueError: invalid literal for int() with base 4: 

### ISSUE THREAD

**Issue by huang-baisha** [plant720/Easy353#7]
Hi,
I meet error during ues easy353, as following.  I do not know why, can you provide me with solution?  Thank you so much！ 

Process Process-3:
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/hbs/software/Easy353/Easy353Lib/filter.py", line 217, in reads_bin_filter
    for file_index in filter_read_for_ref(ref_kmer_dict, k_size, s_size, read_seqs_lst, len(ref_path_lst),
  File "/data/hbs/software/Easy353/Easy353Lib/filter.py", line 170, in filter_read_for_ref
    bin_read_seq, read_len = dnaseq2int(read_seqs_lst[0])
  File "/data/hbs/software/Easy353/Easy353Lib/filter.py", line 76, in dnaseq2int
    return int(dna_seq, 4), len(dna_seq)
ValueError: invalid literal for int() with base 4: '13000021000011020000300030111001030321303112100030030030100011100001111101300300000103010111001110030031311000310000003011100300011001110113020201110FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFF:FF:'
Process Process-6:
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/hbs/software/Easy353/Easy353Lib/filter.py", line 217, in reads_bin_filter
    for file_index in filter_read_for_ref(ref_kmer_dict, k_size, s_size, read_seqs_lst, len(ref_path_lst),
  File "/data/hbs/software/Easy353/Easy353Lib/filter.py", line 170, in filter_read_for_ref
    bin_read_seq, read_len = dnaseq2int(read_seqs_lst[0])
  File "/data/hbs/software/Easy353/Easy353Lib/filter.py", line 76, in dnaseq2int
    return int(dna_seq, 4), len(dna_seq)
ValueError: invalid literal for int() with base 4: '13000021000011020000300030111001030321303112100030030030100011100001111101300300000103010111001110030031311000310000003011100300011001110113020201110FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFF:FF:'
……………………

**Comment by plant720** [comment]
Thank you for reaching out. Providing only the error message makes it challenging to pinpoint the exact issue. If it's not related to the reference file, could you please share the sequencing file and the reference file? This will help us better understand the problem and find a solution for you.
